### ISSUE TITLE
Decay is kinematically forbidden

### ISSUE THREAD

**Issue by ezfisher** [gcowan/RapidSim#11]
Hi, I am using RapidSim in lxplus to simulate the decay of Bs0 -> J/psi phi and it is returning the error that the decay is kinematically forbidden. I see that the issue is for the some reason, the program is assigning the same nonexistent ID number to each particle and giving them a mass of 0 GeV. How do I go about fixing this? I've attached a screenshot of the error that RapidSim keeps throwing.

Thanks,
Eric

![screenshot from 2017-06-14 11-34-33](https://user-images.githubusercontent.com/15036994/27141561-892a33ac-50f6-11e7-8de4-ee8bab2f30e1.png)

**Comment by gcowan** [comment]
The problem is that the “Bs” should be called “Bs0”.

Greig

**Comment by dcraik** [comment]
Hi Eric,

It looks like you've forgotten to set the environment variable $RAPIDSIM_ROOT. This should point to the path where you have installed RapidSim. The particle data is then loaded from $RAPIDSIM_ROOT/config/particles.dat This is also the reason why you're getting warnings from RapidConfig::loadSmearing.

Cheers,
Dan
