### ISSUE TITLE
Installation instructions have typos

### ISSUE THREAD

**Issue by GSarpis** [gcowan/RapidSim#12]
Hello, I tried installing RapidSim, but with the current instructions it doesn't work. I adjusted some lines and made it work:

1.
cmake ../RapidSim (...) --> cmake ../../RapidSim (...)
% This is due to the fact, that previous step asks to "cd build" ending up in ".../RapidSim/build"

2. 
$RAPIDSIM_ROOT/bin/RapidSim.exe $RAPIDSIM_ROOT/bin/validation/Bs2Jpsiphi 10000 1
should be
$RAPIDSIM_ROOT/bin/RapidSim.exe $RAPIDSIM_ROOT/validation/Bs2Jpsiphi 10000 1

%There is no "validation" directory in "bin" it is in general "RapidSim", also example works only with the optional step "make -j4 install", which installs RapidSim.exe into "bin", otherwise it is in "RapidSim/build/src" 

These changes allowed me to install RapidSim and test it. Thank you, Gediminas

**Comment by gcowan** [comment]
Thanks @GSarpis. Can you make a pull request with the relevant changes, please? 

Also, note that RapidSim now comes installed on lxplus, so there is no need to install it yourself if you are happy to work on an lxplus node.

**Comment by dcraik** [comment]
I've gone over the instructions and hopefully fixed this in commit 668bc1d2c14350bbcc72bcae33c9b9c1c6673dbd

The instructions assume the user starts in the same directory as `README.md` so I've left (1) unchanged
