### ISSUE TITLE
RapidSim - reconstructed electron eta always positive 

### ISSUE THREAD

**Issue by bifani** [gcowan/RapidSim#14]
While playing with RapidSim I noticed something odd.

I am generating the decay B+ -> { K1(1270)+ -> {K*0 -> K+ pi-} pi+ } e+ e- in 4pi, but while both the TRUE and RECO eta of the hadrons are distributed between -10 and +10, the RECO eta of the electrons is always >0 (although the corresponding TRUE eta can be <0).

Is there a spurious abs in the electron “reconstruction” or am I missing something?

![kp_eta](https://user-images.githubusercontent.com/17066912/29120069-afccc386-7d00-11e7-8292-a5a097379754.png)
![ep_eta](https://user-images.githubusercontent.com/17066912/29120079-b3cd5b80-7d00-11e7-8f3b-89090f94812c.png)

**Comment by dcraik** [comment]
This is due to a missing line in RapidMomentumSmearHisto::smearMomentum, which is only used by the LHCbElectron smearing model. Fixed in latest github commit.
