### ISSUE TITLE
Add PID information

### ISSUE THREAD

**Issue by gcowan** [gcowan/RapidSim#19]
We should add PID information to the stable particles, based upon histograms in track_P, track_ETA (and potentially other variables) that have been obtained from publicly released LHCb control samples. My initial thoughts about how to do this would be to have a separate evalPID() method in RapidParam (in the same sense as evalMcorr()). Clearly we could have multiple of these functions for different PID hypotheses (or just differentiate between them in a single method). In evalPID() we would only fill a non-zero value of the PID for particles that are stable and have non-zero mass. We would then look-up the PID value corresponding to the particles P, ETA. To prevent opening/closing the ROOT file containing the histogram during each call to evalPID(), we will need a dedicated RapidPID object to hold this information. This should be setup in RapidConfig.

Thoughts?

I have started putting some basics for this into the branch rapidpid, commit 9406b1edb7af67d21e674a44f460182037bfb576

**Comment by particleist** [comment]
The structure sounds correct to me. We need to be able to handle more than one PID variable per particle and their correlations. I think up to two variables per particle is reasonable.

**Comment by gcowan** [comment]
I don't think there is a problem having N different variables for each particle. In the rapidpid branch I have added ProbNNmu, pi, k and p parameters (actually, I should also add electron).

**Comment by particleist** [comment]
I was just talking about the structure in the RapidPID object when evaluating the correlations correctly.

**Comment by gcowan** [comment]
Ahh, OK. Got it.

**Comment by gcowan** [comment]
I've got something that looks reasonable in the rapidpid branch. Please have a look and try to test it. I still need to create some more realistic PID distributions and there is some modification to RapidParticleData required to allow lookup of the sanitised particle names.

**Comment by bifani** [comment]
@gcowan, in case it can help I have the Run1 PIDCalib tuples already produced on the bham cluster (all PID and kinematic vars and sweights for the probe)
Electrons are small (~30MB for ~200k events ), while the other particle species (K, pi, mu and p) are much larger (~80GB in total)

Were you thinking about using histograms (+interpolation) to assign the PID info or something more similar to meerkat?
With histograms I don't think one can handle more than 2 PID vars correlation, and care must be taken with the choice of the binning scheme

Here is a quick example of e_V3ProbNNe:e_Eta:e_PT
![e_v3probnne](https://user-images.githubusercontent.com/17066912/33207775-f0622184-d106-11e7-8c73-f88205fa0782.png)

**Comment by gcowan** [comment]
The current implementation assumes that we use histograms. So, for example, for a particle with the kaon hypothesis, we can get the ProbNNk and ProbNNpi by looking up the relevant histogram that is binned in P and ETA. Can you point me to one of the samples to have a look at? My tests so far have just been using some toy example that I cooked up. It would be good to play with something more realistic.

**Comment by bifani** [comment]
I have put one (small) tuple for each PIDCalib sample in ~simone/public/forGreig
Let me know if you need more info

**Comment by gcowan** [comment]
My latest commit d40c0e6 should be enough for people to test this. Please try it out. I have created some histograms from the PIDCalib sample (10 bins in P, 5 in ETA and 10 in ProbNN). Configuring RapidSim to use them gives plots such as that attached.

Thinking about this a bit more, it might be better to create a dedicated RapidPID object that holds all of the PID information (loaded at run time in RapidConfig), which would be static (sort of like RapidParticleData). This might make it easier to switch to a different implementation of the PID, e.g., from Meerkat. 

Finally, I might need to think a bit more about what to do with simulated particles that fall outside of the (P, ETA) range of the PIDCalib samples. Currently I just use the nearest bin.

![canvas_1](https://user-images.githubusercontent.com/3574317/33218737-681f82d2-d136-11e7-9504-ad1ce2faccb9.png)

**Comment by bifani** [comment]
@gcowan , the plot looks odd to me
Did you use the sWeights to produce the maps (e.g. `RSDStCalib->Draw("K_V2ProbNNK>>(10,0,1)","nsig_sw")`?
I would also suggest to use some sort of interpolation when sampling the histogram, the simplest being https://root.cern.ch/doc/master/classTH3.html#ad6e3388d1f127f018941f932a50a3e2d

Btw, for all particles except electrons we can easily have a much finer binning (the stats I gave you is only ~1/200 of the total)

**Comment by gcowan** [comment]
Ahh, I forgot to sWeight the samples. This is now done 05f5487, although it looks like I will need to put in better protection for bins with negative entries (hopefully the goes away with larger samples).

I sample from the TH1D ProbNN histogram, obtained from the TH3D via ProjectionZ(), by doing GetRandom(). Not clear to me that interpolation makes sense here? Like you say, we can increase the binning anyway.

**Comment by bifani** [comment]
my bad , I was thinking about implementing this in a different way but it turned out to make no sense :p

surely more stats will remove the negative entries and more bins will help smoothing the final distribution
I don't think it's a good idea to pass you 80GB of tuples, but if you wish I could run in the local cluster the script you used to produce the TH3

to get the correlation among PID vars do you have a better idea than THnSparse?

**Comment by particleist** [comment]
Hey, will get around to testing this soon. For PID information in regions not covered by the samples, I guess nearest-neighbour is the only realistic approach.

**Comment by gcowan** [comment]
This is now done and a new version has been released (v1.4). There may still be issue regarding the optimal binning to use for the samples (and whether to try to use THnSparse at some point) but new issues can be raised for them.
