### ISSUE TITLE
Generation with baryons

### ISSUE THREAD

**Issue by alexpearce** [gcowan/RapidSim#2]
Firstly: thanks a lot for the nice package 😄 

I'm using it to generate phase space for the chain Λb0 → Λc+ μν, with Λc+ → ph-h+. The executable runs and produces output (always a good start), and, comparing the distributions with some data, things are looking pretty nice. (The data isn't efficiency-corrected, but things look ‘reasonable enough’ to me.)

I'm planning to open a PR soon to add some baryons to the particle data file, but in the meantime I'd just like to check: is there any reason why the package can't/shouldn't be used for simulating baryonic decays, as it is now?

**Comment by gcowan** [comment]
Excellent, glad to hear that you are using the package and that it is working. No reason that it can't be used to simulate baryonic decays. Please go ahead with any PR's and let us know if you have any questions.

**Comment by alexpearce** [comment]
Thanks! That's good to hear. I'll open a PR ASAP.
