### ISSUE TITLE
Add ability to handle photons?

### ISSUE THREAD

**Issue by particleist** [gcowan/RapidSim#22]
It would be good to add the ability to have a special set of variables stored for photons, and a specific calorimeter energy smearing for these (that is trivial and publically available). In the first instance adding a "paramsNeutral" list to the config file of the decays would be a solution. But how would we handle merged/resolved pi0s?

**Comment by gcowan** [comment]
I have implemented a new class to smear a particle's energy according to the constants found in a new LHCbPhoton config file. This is configured for a particular particle in the same way as a specific momentum smearing.
