### ISSUE TITLE
Add pileup

### ISSUE THREAD

**Issue by particleist** [gcowan/RapidSim#23]
Should add the generation of pileup primary vertices, and add a variable called "MINIP" which gives the minimum impact parameter with respect to any PV, while "IP" should continue to be the IP wrt. the actual parent PV of the particle. In the first instance SIGMAIP should remain the same for both, subsequently if we decide to smear PVs and SVs this would need to be revisited.

**Comment by particleist** [comment]
One decision to make is whether to smear the IP separately for the actual parent PV and the next closest PV. I am tempted to smear it separately (throw the random number again) but what do you think?

Notice that the definition of what is the "minIP" would in this logic be based on true, not smeared information. That's not obviously what you actually want. Thoughts?

**Comment by particleist** [comment]
OK thinking more about this the IP should definitely be smeared separately for the parent and closest PV, and the respective IP/SigmaIP stored. That's easy enough. How to define minIP based on the smeared info, which is what we I think want, is less clear to me.

**Comment by particleist** [comment]
Also, I am not sure why in master SIGMAIP is set to be neither "truth" nor "smeared" type of information. That I guess is a bug (it should be truth only).

**Comment by particleist** [comment]
Also as part of this should change the logic of the SIGMAIP variable. In the last version it returned the mean sigma for a given particle's PT. It is more realistic to return the actual sigma thrown for a specific particle by the random number generator, since having a Kalman fitted track and vertex implies that we have accurate covariance matrices for this specific momentum and this specific amount of multiple scattering etc.

**Comment by dcraik** [comment]
In master from commit 593073d2b5e401abcc7654a50a2742167cb47e5d
