### ISSUE TITLE
Implement ReDecay in RapidSim

### ISSUE THREAD

**Issue by particleist** [gcowan/RapidSim#26]
One good use case for RapidSim could be for ultra-high statistics verification of ReDecay, in particular the accuracy of the uncertainties following its bootstrapping procedure. It should be fairly simple to add a global ReDecay tag which simply redoes the signal decay but keeps the B kinematics the same each time. This should be then paired with an event number saving in order to be able to implement the bootstrap later.

**Comment by gcowan** [comment]
Closed after 1735ef5
