### ISSUE TITLE
Bugs in RapidDecay::getParticleIP and pileup

### ISSUE THREAD

**Issue by dcraik** [gcowan/RapidSim#31]
The distance between a point (x0) and a line (defined by points x1 and x2) should be:
| (x0-x1) x (x0-x2) | / | x2-x1 |

but the code in RapidDecay::getParticleIP has x1 = dv, x2 = 2 dv + p (instead of dv + p).

I spent a while trying to figure out why this wasn't causing a bug and then I realised that pv is always (0,0,0) so the extra (pv - dv) x dv part is always (0,0,0).

To test this, I tried turning up the pileup but was unable to get any pileup PVs. At this point i checked beam->getPileup() and found it was set to zero.

**Comment by dcraik** [comment]
I've got a fix for this but need to delete a lot of debug output and do some further testing before committing.

We should hold off on GenSer release for 1.4.1 and release 1.4.2 once this is committed.

**Comment by particleist** [comment]
Grr that's embarassing. Good spot!

**Comment by particleist** [comment]
I've fixed these on the rapidredecay branch now, if you want to compare with your own fix @dcraik

**Comment by dcraik** [comment]
Fix looks good
