### ISSUE TITLE
Add sampling from distribution of PVNTRACKS

### ISSUE THREAD

**Issue by gcowan** [gcowan/RapidSim#39]
Need some representative distribution (background subtracted) of PVNTRACKS to sample from when getting the resolution for the PV. This should be a public distribution if possible.

**Comment by gcowan** [comment]
Another update: the distribution of PVNTRACKS basically comes from Figure 25 of this document https://arxiv.org/pdf/1412.6352.pdf

**Comment by dcraik** [comment]
Merged to master
