### ISSUE TITLE
Momentum smearing model

### ISSUE THREAD

**Issue by alexpearce** [gcowan/RapidSim#4]
The README states that “the daughter particle momenta are smeared correctly”. I'd like to know what this really means.

After some digging through the code, I think that the momentum smearing is defined by `TGraph` objects in ROOT files in [`rootfiles/smear`](https://github.com/gcowan/RapidSim/tree/ed1461039a9fd0c8b5a3702081d48357cf5ca42d/rootfiles/smear). The file `smear12.root` in that folder contains three `TGraph` objects: `mc`, `data`, and `res`. How were the datapoints in these graphs obtained?

**Comment by gcowan** [comment]
Hi Alex,

Just following up on this. Please see my presentation in the simulation meeting this week for more details.

Greig

**Comment by alexpearce** [comment]
Thank you! [Link for the lazy](https://indico.cern.ch/event/605657/contributions/2441115/).
