### ISSUE TITLE
Include invisible particles in acceptance cut?

### ISSUE THREAD

**Issue by alexpearce** [gcowan/RapidSim#5]
The [`allInAcceptance` method](https://github.com/gcowan/RapidSim/blob/ed1461039a9fd0c8b5a3702081d48357cf5ca42d/src/RapidAcceptance.cc#L73-L80), applied to a decay when `AllIn` is specified in the config file, applies the [acceptance requirements](https://github.com/gcowan/RapidSim/blob/ed1461039a9fd0c8b5a3702081d48357cf5ca42d/src/RapidAcceptance.cc#L93-L102) to all particles in the decay.

Generally, you don't care if particles that you cannot detect go outside of your acceptance. Should `allInAcceptance` ignore invisible particles? It would be little sneaky as then the method wouldn't really be checking ‘all’ particles, but it's maybe more pragmatic.

**Comment by dcraik** [comment]
I agree there should be a "`visibleInAcceptance`" (either replacing or in addition to `allInAcceptance`). The easiest fix is to only add visible particles to the `parts_` vector in `setup` and make clear in the documentation that invisible particles are ignored. If we want to retain both functionalities we should add a second vector to avoid performing the checks each time.

I'm currently leaning towards replacing the existing method - the only case I can think of for keeping the existing functionality is to investigate the effect of invisible daughters on the `motherInAcceptance` requirement but this could be easily replicated by making the daughters visible.
