### ISSUE TITLE
Failure of the "make -j 4"

### ISSUE THREAD

**Issue by mkozeiha** [gcowan/RapidSim#8]
[output.txt](https://github.com/gcowan/RapidSim/files/800062/output.txt)

Dear experts

I am facing some problems concerning the setup of the RapidSim, please see the attached file.
I have followed the instructions in the README  but I obtained some errors mainly like " -bash: /afs/cern.ch/user/m/mkozeiha/RapidSim/build/src/RapidSim.exe: No such file or directory"

So could some one please give  me some ideas of what is going on and how to solve it.

Kind regards 
Mohamad

**Comment by gcowan** [comment]
Dear Mohamed,

I think you have a problem with the compilation. Please ensure you have the ROOT application setup properly, as well as GSL. The relevant environment variables need to be configured (i.e., ROOTSYS).

Greig

**Comment by mkozeiha** [comment]
Dear Greig


I am sorry again for this issue, I have tried the same commands that are presented in the "https://github.com/gcowan/RapidSim/tree/1"  to make the setup procedure, but again I have this error.
I can't figure out what is going on.
*******************************************************************************************************************
[mkozeiha@lxplus020 build]$ make 
Scanning dependencies of target RapidSim
[  5%] Building CXX object src/CMakeFiles/RapidSim.dir/RooGounarisSakurai.cc.o
[ 11%] Building CXX object src/CMakeFiles/RapidSim.dir/RooRelBreitWigner.cc.o
[ 17%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidAcceptance.cc.o
[ 23%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidAcceptanceLHCb.cc.o
[ 29%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidConfig.cc.o
[ 35%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidCut.cc.o
[ 41%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidDecay.cc.o
[ 47%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidHistWriter.cc.o
[ 52%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidMomentumSmearGauss.cc.o
[ 58%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidMomentumSmearGaussPtEtaDep.cc.o
[ 64%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidMomentumSmearHisto.cc.o
[ 70%] Building CXX object src/CMakeFiles/RapidSim.dir/RapidParam.cc.o
/afs/cern.ch/user/m/mkozeiha/RapidSim/src/RapidParam.cc: In member function ‘double RapidParam::evalCorrectedMass()’:
/afs/cern.ch/user/m/mkozeiha/RapidSim/src/RapidParam.cc:92:9: error: unused variable ‘pLong’ [-Werror=unused-variable]
  double pLong  = TMath::Abs(cosDir * momS.P());
         ^
/afs/cern.ch/user/m/mkozeiha/RapidSim/src/RapidParam.cc:98:9: error: unused variable ‘mMiss2’ [-Werror=unused-variable]
  double mMiss2 = mPar2 - mVis2;
         ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/RapidSim.dir/RapidParam.cc.o] Error 1
make[1]: *** [src/CMakeFiles/RapidSim.dir/all] Error 2
make: *** [all] Error 2
[mkozeiha@lxplus020 build]$
*************************************************************************************************************************
Thank you in advance.

Kind regards 
Mohamad

**Comment by gcowan** [comment]
Dear Mohamad,

You are using the wrong C++ compiler. Please use gcc v4.9 or above. Alternatively you can use clang.

Greig

**Comment by gcowan** [comment]
Hi Mohamad,

Also, we just spotted a bug in the master version of the code. I have updated RapidParam.cc it so you can try to git pull to get the latest version.

Greig

**Comment by mkozeiha** [comment]
Dear Greig

Thank you for the answer, every thing works well when I get the latest version.
Thank you again.


Kind regards 
Mohamad
