### ISSUE TITLE
Rapidsim test fails for gcc62 and gcc7

### ISSUE THREAD

**Issue by gcowan** [gcowan/RapidSim#9]
It seems that it gives a bit different numerical values and some chi2 tests fail:

INFO in compareHstograms : Jpsi_M_TRUE :	chi2 = 0.992849
WARNING in compareHistograms : Histograms do not match for Jpsi_M_TRUE

INFO in compareHstograms : Jpsi_M_TRUE_Kp2pip :	chi2 = 0.992849
WARNING in compareHistograms : Histograms do not match for Jpsi_M_TRUE_Kp2pip

INFO in compareHstograms : Jpsi_M_TRUE_Km2pim :	chi2 = 0.992849
WARNING in compareHistograms : Histograms do not match for Jpsi_M_TRUE_Km2pim

INFO in compareHstograms : Jpsi_M_TRUE_Kp2pip_Km2pim :	chi2 = 0.992849
WARNING in compareHistograms : Histograms do not match for Jpsi_M_TRUE_Kp2pip_Km2pim

INFO in compareHstograms : D0_M_TRUE :	chi2 = 0.996322
WARNING in compareHistograms : Histograms do not match for D0_M_TRUE

Full test output can be found here:

http://cdash.cern.ch/testDetails.php?test=25017933&build=354645

**Comment by dcraik** [comment]
As of commit ce78327a63ef31a12d8d604703c1f42a6439c2a3, validation script no longer requires histograms to exactly match - simply that the average p-value for all histograms is larger than 0.1

This should fix this issue
